### PR TITLE
Feature/pages setup

### PR DESCRIPTION
**Pull request by Diegobr21**

### CODE REVIEW

**Review by AbiudSM — COMMENTED** [review]
Nice commit bro

**Review by DanielFL0 — APPROVED** [review]
Nice work on the front end! Everything is looking good so far, I approve this. However I am going to be checking Elecritic.sln, was that file generated by Visual Studio? It looks weird.

**Comment by Diegobr21** [comment]
Elecritic.sln is a VS-generated file indeed

**Comment by Diegobr21** [comment]
> Nice work on the front end! Everything is looking good so far, I approve this. However I am going to be checking Elecritic.sln, was that file generated by Visual Studio? It looks weird.

> Elecritic.sln is a VS-generated file indeed

**Pull request merged**
