### PR TITLE
Services classes are now in a dedicated folder

### PR DESCRIPTION
**Pull request by netotz**
I moved services to a folder. The main reason behind this is to add the database class in the Services folder.

### CODE REVIEW

**Comment by DanielFL0** [comment]
Is this related to an existing issue?

**Comment by netotz** [comment]
@DanielFL0  no, it's just a file organization for better context, and because I'll add the database class to the new Services folder

**Comment by DanielFL0** [comment]
Oh, I get it now, I'll label this as an enhancement and approve your request.

**Review by DanielFL0 — APPROVED** [review]
Great work! Thanks @netotz >w<b

**Pull request merged**
