### PR TITLE
Changed product category to a badge pill [PROPOSAL]

### PR DESCRIPTION
**Pull request by DanielFL0**
### Objective
Good websites commonly use design patterns that enable the user to receive essential information with minimal effort, I believe that by thinking in the way the user needs to see the information this will allow us to create a product which the user won't struggle using. 
By taking into account the user's thought process and the website's current design I've come up with some slight changes that might improve the user experience.
### Changes
**Before**
Product
**After**
badge
By providing the product information in one single place the user is more likely to waste less time searching for the information.

### CODE REVIEW

**Comment by netotz** [comment]
Looks very cool! Also as we discussed earlier you can remove the tiles _Fabricante_ and _Categoría_ to avoid redundancies, and show the company with a different font, and I'd prefer a better title for the product description, may be _Detalles_ or _Especificaciones_? What do you think?

**Comment by DanielFL0** [comment]
> Looks very cool! Also as we discussed earlier you can remove the tiles _Fabricante_ and _Categoría_ to avoid redundancies, and show the company with a different font, and I'd prefer a better title for the product description, may be _Detalles_ or _Especificaciones_? What do you think?

I agree, I think _Especificaciones_ is a better fit, and yes I will remove the titles _Fabricante_ and _Categoría_. Thanks a lot for your input!

**Comment by DanielFL0** [comment]
### Changes
badgev2
**Added**
+Favorite button position
+Favorite button color
**Removed**
-_Fabricante_ title
-_Categoría_ title

**Comment by DanielFL0** [comment]
### Changes V1
badgev3
**Changes**
+Changed Button outline warning to Button warning.

**Review by netotz — APPROVED** [review]
It really looks very cool man

**Pull request merged**
